version: '3.8'
services:
  db0:
    image: postgres:15
    container_name: db_0
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database0
    volumes:
      - db_data_0:/var/lib/postgresql/data

  db1:
    image: postgres:15
    container_name: db_1
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database1
    volumes:
      - db_data_1:/var/lib/postgresql/data

  db2:
    image: postgres:15
    container_name: db_2
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database2
    volumes:
      - db_data_2:/var/lib/postgresql/data

  db3:
    image: postgres:15
    container_name: db_3
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database3
    volumes:
      - db_data_3:/var/lib/postgresql/data

  db4:
    image: postgres:15
    container_name: db_4
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database4
    volumes:
      - db_data_4:/var/lib/postgresql/data

  db5:
    image: postgres:15
    container_name: db_5
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database5
    volumes:
      - db_data_5:/var/lib/postgresql/data

  db6:
    image: postgres:15
    container_name: db_6
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database6
    volumes:
      - db_data_6:/var/lib/postgresql/data

  db7:
    image: postgres:15
    container_name: db_7
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database7
    volumes:
      - db_data_7:/var/lib/postgresql/data

  db8:
    image: postgres:15
    container_name: db_8
    ports:
      - "5441:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database8
    volumes:
      - db_data_8:/var/lib/postgresql/data

  db9:
    image: postgres:15
    container_name: db_9
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database9
    volumes:
      - db_data_9:/var/lib/postgresql/data

  db10:
    image: postgres:15
    container_name: db_10
    ports:
      - "5443:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database10
    volumes:
      - db_data_10:/var/lib/postgresql/data

  db11:
    image: postgres:15
    container_name: db_11
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database11
    volumes:
      - db_data_11:/var/lib/postgresql/data

  db12:
    image: postgres:15
    container_name: db_12
    ports:
      - "5445:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database12
    volumes:
      - db_data_12:/var/lib/postgresql/data

  db13:
    image: postgres:15
    container_name: db_13
    ports:
      - "5446:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database13
    volumes:
      - db_data_13:/var/lib/postgresql/data

  db14:
    image: postgres:15
    container_name: db_14
    ports:
      - "5447:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database14
    volumes:
      - db_data_14:/var/lib/postgresql/data

  db15:
    image: postgres:15
    container_name: db_15
    ports:
      - "5448:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database15
    volumes:
      - db_data_15:/var/lib/postgresql/data

  db16:
    image: postgres:15
    container_name: db_16
    ports:
      - "5449:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database16
    volumes:
      - db_data_16:/var/lib/postgresql/data

  db17:
    image: postgres:15
    container_name: db_17
    ports:
      - "5450:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database17
    volumes:
      - db_data_17:/var/lib/postgresql/data

  db18:
    image: postgres:15
    container_name: db_18
    ports:
      - "5451:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database18
    volumes:
      - db_data_18:/var/lib/postgresql/data

  db19:
    image: postgres:15
    container_name: db_19
    ports:
      - "5452:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database19
    volumes:
      - db_data_19:/var/lib/postgresql/data

  db20:
    image: postgres:15
    container_name: db_20
    ports:
      - "5453:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database20
    volumes:
      - db_data_20:/var/lib/postgresql/data

  db21:
    image: postgres:15
    container_name: db_21
    ports:
      - "5454:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database21
    volumes:
      - db_data_21:/var/lib/postgresql/data

  db22:
    image: postgres:15
    container_name: db_22
    ports:
      - "5455:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database22
    volumes:
      - db_data_22:/var/lib/postgresql/data

  db23:
    image: postgres:15
    container_name: db_23
    ports:
      - "5456:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database23
    volumes:
      - db_data_23:/var/lib/postgresql/data

  db24:
    image: postgres:15
    container_name: db_24
    ports:
      - "5457:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database24
    volumes:
      - db_data_24:/var/lib/postgresql/data

  db25:
    image: postgres:15
    container_name: db_25
    ports:
      - "5458:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database25
    volumes:
      - db_data_25:/var/lib/postgresql/data

  db26:
    image: postgres:15
    container_name: db_26
    ports:
      - "5459:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database26
    volumes:
      - db_data_26:/var/lib/postgresql/data

  db27:
    image: postgres:15
    container_name: db_27
    ports:
      - "5460:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database27
    volumes:
      - db_data_27:/var/lib/postgresql/data

  db28:
    image: postgres:15
    container_name: db_28
    ports:
      - "5461:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database28
    volumes:
      - db_data_28:/var/lib/postgresql/data

  db29:
    image: postgres:15
    container_name: db_29
    ports:
      - "5462:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database29
    volumes:
      - db_data_29:/var/lib/postgresql/data

  db30:
    image: postgres:15
    container_name: db_30
    ports:
      - "5463:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database30
    volumes:
      - db_data_30:/var/lib/postgresql/data

  db31:
    image: postgres:15
    container_name: db_31
    ports:
      - "5464:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database31
    volumes:
      - db_data_31:/var/lib/postgresql/data

  db32:
    image: postgres:15
    container_name: db_32
    ports:
      - "5465:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database32
    volumes:
      - db_data_32:/var/lib/postgresql/data

  db33:
    image: postgres:15
    container_name: db_33
    ports:
      - "5466:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database33
    volumes:
      - db_data_33:/var/lib/postgresql/data

  db34:
    image: postgres:15
    container_name: db_34
    ports:
      - "5467:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database34
    volumes:
      - db_data_34:/var/lib/postgresql/data

  db35:
    image: postgres:15
    container_name: db_35
    ports:
      - "5468:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database35
    volumes:
      - db_data_35:/var/lib/postgresql/data

  db36:
    image: postgres:15
    container_name: db_36
    ports:
      - "5469:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database36
    volumes:
      - db_data_36:/var/lib/postgresql/data

  db37:
    image: postgres:15
    container_name: db_37
    ports:
      - "5470:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database37
    volumes:
      - db_data_37:/var/lib/postgresql/data

  db38:
    image: postgres:15
    container_name: db_38
    ports:
      - "5471:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database38
    volumes:
      - db_data_38:/var/lib/postgresql/data

  db39:
    image: postgres:15
    container_name: db_39
    ports:
      - "5472:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database39
    volumes:
      - db_data_39:/var/lib/postgresql/data

  db40:
    image: postgres:15
    container_name: db_40
    ports:
      - "5473:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database40
    volumes:
      - db_data_40:/var/lib/postgresql/data

  db41:
    image: postgres:15
    container_name: db_41
    ports:
      - "5474:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database41
    volumes:
      - db_data_41:/var/lib/postgresql/data

  db42:
    image: postgres:15
    container_name: db_42
    ports:
      - "5475:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database42
    volumes:
      - db_data_42:/var/lib/postgresql/data

  db43:
    image: postgres:15
    container_name: db_43
    ports:
      - "5476:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database43
    volumes:
      - db_data_43:/var/lib/postgresql/data

  db44:
    image: postgres:15
    container_name: db_44
    ports:
      - "5477:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database44
    volumes:
      - db_data_44:/var/lib/postgresql/data

  db45:
    image: postgres:15
    container_name: db_45
    ports:
      - "5478:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database45
    volumes:
      - db_data_45:/var/lib/postgresql/data

  db46:
    image: postgres:15
    container_name: db_46
    ports:
      - "5479:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database46
    volumes:
      - db_data_46:/var/lib/postgresql/data

  db47:
    image: postgres:15
    container_name: db_47
    ports:
      - "5480:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database47
    volumes:
      - db_data_47:/var/lib/postgresql/data

  db48:
    image: postgres:15
    container_name: db_48
    ports:
      - "5481:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database48
    volumes:
      - db_data_48:/var/lib/postgresql/data

  db49:
    image: postgres:15
    container_name: db_49
    ports:
      - "5482:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database49
    volumes:
      - db_data_49:/var/lib/postgresql/data

volumes:
  db_data_0:
  db_data_1:
  db_data_2:
  db_data_3:
  db_data_4:
  db_data_5:
  db_data_6:
  db_data_7:
  db_data_8:
  db_data_9:
  db_data_10:
  db_data_11:
  db_data_12:
  db_data_13:
  db_data_14:
  db_data_15:
  db_data_16:
  db_data_17:
  db_data_18:
  db_data_19:
  db_data_20:
  db_data_21:
  db_data_22:
  db_data_23:
  db_data_24:
  db_data_25:
  db_data_26:
  db_data_27:
  db_data_28:
  db_data_29:
  db_data_30:
  db_data_31:
  db_data_32:
  db_data_33:
  db_data_34:
  db_data_35:
  db_data_36:
  db_data_37:
  db_data_38:
  db_data_39:
  db_data_40:
  db_data_41:
  db_data_42:
  db_data_43:
  db_data_44:
  db_data_45:
  db_data_46:
  db_data_47:
  db_data_48:
  db_data_49:
